---
- hosts: prod-server
  remote_user: ubuntu
  vars:
    http_port: 80
    image_name: www.myregistrydomain.com/vodafone-demo
  tasks:
    - name: run kill all script
      script: ./../scripts/kill_all.sh {{ image_name }}

    - name: login to docker registry
      shell: "docker login https://www.myregistrydomain.com -u admin -p admin"

    - name: pull the latest app image
      shell: "docker pull {{ image_name }}"

    - name: run the container and start app
      shell: "docker run -id -p {{ http_port }}:3000 {{ image_name }}"
